### ISSUE TITLE
first issue no MAP 👎 

### ISSUE THREAD

**Issue by Programer3** [Programer3/Mountain_bike_HD#5]
`No map >: ( `
@krishnasingh34 
#4 

ALL ABOVE IS FOR LEARNING FOR MY TEAM

**Comment by Programer3** [comment]
1st comment #5

**Comment by saniyadutta266** [comment]
#3

**Comment by Programer3** [comment]
Added it by Myself after some research HERE → aa9e842e806e7b1663d9a45218812e75c9a5e93c
![grass](https://github.com/Programer3/Mountain_bike_HD/assets/68413771/b0596061-dd79-4f53-9def-f0e6e0cd79b7)
